app/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
	path('', views.home, name='home'),
	path('new_search', views.new_search, name='new_search'),
	path('about', views.about, name='about'),
]

codelist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
	search = models.CharField(max_length=500)
	created = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.search

app/views.py
from django.shortcuts import render
from django.urls import reverse

import requests
from requests.compat import quote_plus 
from bs4 import BeautifulSoup
from . import models



CRAIGLIST_URL = 'https://newyork.craigslist.org/search/{}?query={}&sort={}&lang=en&cc=gb'
IMAGE_URL = 'https://images.craigslist.org/{}_300x300.jpg'

def home(request):
	return render(request, 'base.html')

def about(request):
	return render(request, 'app/about.html')

def new_search(request):
	# get keyword search
	search = request.POST.get('search')
	# another option
	category = request.POST.get('category')
	sort = request.POST.get('filter')
	# getting the webpage
	url = CRAIGLIST_URL.format(category, quote_plus(search), sort)
	response = requests.get(url)
	# passing the source code
	soup = BeautifulSoup(response.text, features='html.parser')
	# extract all post
	post_lists = soup.find_all('li', {'class': 'result-row'})

	result_posts = []
	for post in post_lists:
		try:
			title = post.find(class_='result-title').text
			url = post.find('a').get('href')
			price = 'N/A'
			image_url = 'https://stickershop.line-scdn.net/stickershop/v1/product/1000415/LINEStorePC/main.png;compress=true'

			if post.find(class_='result-price'):
				price = post.find(class_='result-price').text

			if post.find(class_='result-image'):
				ids = post.find(class_='result-image').get('data-ids')
				image_url = ids.split(",")[0].split(":")[1]
				image_url = IMAGE_URL.format(image_url)

			result_posts.append((title, url, price, image_url))
		except:
			print('Error')

	data = {
		'search': search,
		'posts': result_posts,
	}
	return render(request, 'app/new_search.html', data)

templates/app/about.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>About</title>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
	<div class="nav-wrapper">
	  <a href="#!" class="brand-logo">CodeList</a>
	  <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
	  <ul class="right hide-on-med-and-down">
	    <li><a href="/">Home</a></li>
		<li><a href="{% url 'app:about' %}">About</a></li>
	  </ul>
	</div>
</nav>
<ul class="sidenav" id="mobile-demo">
	<li><a href="/">Home</a></li>
	<li><a href="{% url 'app:about' %}">About</a></li>
</ul>
	<div class="container">
		<div class="row">
			<div class="card large">
				<div class="card-content">
					<div class="card-title">
						About
					</div>
					
					<p>
						Author: Fikri Rudiansyah
					</p>
					<p>
						Github: <a href="https://github.com/superXdev/codelist">https://github.com/superXdev/codelist</a>
					</p>
					<p>
						Web: <a href="https://fikridev.tech/">https://fikridev.tech</a>
					</p>
					<div style="margin-top: 10px">
						<p>Lorem ipsum, dolor sit amet, consectetur adipisicing elit. Perferendis quod aut expedita magni quibusdam facilis corrupti consequuntur modi ducimus aperiam exercitationem repellendus, voluptatem adipisci nostrum nemo veritatis at. Ratione quidem eaque facilis necessitatibus odio similique dolorum numquam, tempora nesciunt magni?</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

templates/app/new_search.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load static %}

{% block content %}
	<h5 class="center">{{ search | title }}</h5>

	<div class="row">
		{% for post in posts %}
		<div class="col s4">
			<div class="card medium">
				<div class="card-image">
					<img src="{{ post.3 }}" class="responsive-img">
				</div>
				<div class="card-content">
					<h7>{{ post.0 }}</h7>
					<p class="green-text text-darken-1">{{ post.2 }}</p>
				</div>
				<div class="card-action">
					<a href="{{ post.1 }}" target="_blank">view</a>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Home</title>
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav>
	<div class="nav-wrapper">
	  <a href="#!" class="brand-logo">CodeList</a>
	  <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
	  <ul class="right hide-on-med-and-down">
	    <li><a href="/">Home</a></li>
		<li><a href="{% url 'app:about' %}">About</a></li>
	  </ul>
	</div>
</nav>
<ul class="sidenav" id="mobile-demo">
	<li><a href="/">Home</a></li>
	<li><a href="{% url 'app:about' %}">About</a></li>
</ul>

{# just a home text #}
<div class="container">
	<h3 class="center">Search on craigslist</h3>

	<div class="row">
		<div class="col s4 center">
			<i class="large material-icons red-text text-darken-1">flash_on</i>
			<p>Fast web scrapper.</p>
		</div>
		<div class="col s4 center">
			<i class="large material-icons green-text text-darken-1">mood</i>
			<p>Simple UI.</p>
		</div>
		<div class="col s4 center">
			<i class="large material-icons light-blue-text">link</i>
			<p>Jump to the link.</p>
		</div>
	</div>


	{# search section #}
	<div class="center">
		<form action="{% url 'app:new_search' %}" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col s12">
					<input type="text" placeholder="Search something.." name="search" autocomplete="off">
				</div>

				<div class="input-field col s6">
				    <select name="category">
				      <option value="sss" selected>all</option>
	                    <option value="ata">antiques</option>
	                    <option value="ppa">appliances</option>
	                    <option value="ara">arts+crafts</option>
	                    <option value="sna">atvs/utvs/snow</option>
	                    <option value="pta">auto parts</option>
	                    <option value="wta">auto wheels &amp; tyres</option>
	                    <option value="ava">aviation</option>
	                    <option value="baa">baby+kid</option>
	                    <option value="bar">barter</option>
	                    <option value="haa">beauty+hlth</option>
	                    <option value="bip">bike parts</option>
	                    <option value="bia">bikes</option>
	                    <option value="bpa">boat parts</option>
	                    <option value="boo">boats</option>
	                    <option value="bka">books</option>
	                    <option value="bfa">business</option>
	                    <option value="cta">cars+vans</option>
	                    <option value="ema">cds/dvd/vhs</option>
	                    <option value="cla">clothes+acc</option>
	                    <option value="cba">collectibles</option>
	                    <option value="syp">computer parts</option>
	                    <option value="sya">computers</option>
	                    <option value="ela">electronics</option>
	                    <option value="gra">farm+garden</option>
	                    <option value="zip">free stuff</option>
	                    <option value="fua">furniture</option>
	                    <option value="gms">garage sales</option>
	                    <option value="foa">general</option>
	                    <option value="hva">heavy equipment</option>
	                    <option value="hsa">household</option>
	                    <option value="jwa">jewellery</option>
	                    <option value="maa">materials</option>
	                    <option value="moa">mobile phones</option>
	                    <option value="rva">motor homes/campers</option>
	                    <option value="mpa">motorcycle parts</option>
	                    <option value="mca">motorcycles</option>
	                    <option value="msa">music instr</option>
	                    <option value="pha">photo+video</option>
	                    <option value="sga">sporting</option>
	                    <option value="tia">tickets</option>
	                    <option value="tla">tools</option>
	                    <option value="taa">toys+games</option>
	                    <option value="tra">trailers</option>
	                    <option value="vga">video gaming</option>
	                    <option value="waa">wanted</option>
				    </select>
				    <label>Select category</label>
			  </div>
			  <div class=" input-field col s6">
			  	<select name="filter">
			  		<option value="date">Newest</option>
			  		<option value="rel">Most relevant</option>
			  	</select>
			  	<label>Sort by</label>
			  </div>
			</div>
			
			<button type="submit" class="btn waves-effect waves-light">Submit</button>
		</form>
	</div>

	{% block content %}

	{% endblock %}
</div>



<script src="{% static 'js/materialize.min.js' %}"></script>
<script>
	document.addEventListener('DOMContentLoaded', function() {
	    var elems = document.querySelectorAll('select');
	    var instances = M.FormSelect.init(elems);
	});

	document.addEventListener('DOMContentLoaded', function() {
	   var elems = document.querySelectorAll('.sidenav');
	   var instances = M.Sidenav.init(elems);
	});
</script>
</body>
</html>